# Generated by Django 4.2 on 2024-02-09 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dentalapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reg',
            name='uname',
        ),
    ]
