# Generated by Django 4.2 on 2024-03-16 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dentalapp', '0002_remove_reg_uname'),
    ]

    operations = [
        migrations.CreateModel(
            name='normal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='normalteeth/')),
            ],
        ),
        migrations.CreateModel(
            name='xray',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='xrayteeth/')),
            ],
        ),
        migrations.AddField(
            model_name='reg',
            name='uname',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
