# Generated by Django 4.2 on 2024-03-16 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dentalapp', '0003_normal_xray_reg_uname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='xray',
            old_name='img',
            new_name='ximg',
        ),
    ]
